### PR TITLE
v1.0.0-rc2

### PR DESCRIPTION
**Pull request by limonte**
- add 'bower install' to npm postinstall hook
- enabled automatically publishing of npm package

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/115)

### CODE REVIEW

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/115#-:-KZ6sa4OA68aEj0ZHgiS:bnfp4nl)*

**Comment by Chabane** [comment]
Thanks,

Waiting for publication on npm :-)

**Comment by Chabane** [comment]
I have an error when I use npm install --save @vaadin/angular2-polymer@1.0.0-rc2.

`bower ENOENT No bower.json present`

**Comment by limonte** [comment]
@Chabane sorry for this issue. I've bumped version to [v1.0.0-rc3](https://github.com/vaadin/angular2-polymer/releases/tag/v1.0.0-rc3)

**Comment by Chabane** [comment]
Thanks, it works :+1:

**Pull request merged**
