### PR TITLE
Add instructions to support Angular v.2.2.0

### LINKED ISSUE #106: Document light DOM limitations and workaround for Angular v2.2+
Starting from Angular v2.2+, in order to make light DOM of Polymer elements work as expected, users have to switch Polymer to Shadow DOM mode and use the full Shadow DOM v0 polyfill.

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #106

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/107)

### CODE REVIEW

**Comment by platosha** [comment]
Please don’t forget to update the `angular2-polymer-quickstart` app as well.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/ng-cli-webpack.adoc, line 102 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBR0Egf-l2A8youI8o:-KXBR0Egf-l2A8youI8p:bmkgvnc) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/ng-cli-webpack.adoc#L102)):*
> ```AsciiDoc
>   <script src="assets/bower_components/webcomponentsjs/webcomponents.min.js"></script>
>   <script>
>     // this script must run before Polymer is imported
> ```

Maybe try without this comment first?

---

*[docs/ng-cli-webpack.adoc, line 105 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBRAz7Pb9nb7rZVY0z:-KXBRAz7Pb9nb7rZVY1-:bjru3ik) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/ng-cli-webpack.adoc#L105)):*
> ```AsciiDoc
>     window.Polymer = {
>       dom: 'shadow'
>     }
> ```

Although not required, it would be nice to have a semicolon here.

---

*[docs/overview.adoc, line 33 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBR3hASAxXoDXlreo4:-KXBR3hASAxXoDXlreo5:bq3g697) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/overview.adoc#L33)):*
> ```AsciiDoc
> <script src="bower_components/webcomponentsjs/webcomponents.min.js"></script>
> <script>
>   // this script must run before Polymer is imported
> ```

Same here ^^^.

---

*[docs/overview.adoc, line 36 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBRHMoMhKQTiJXv7Nm:-KXBRHMoMhKQTiJXv7Nn:b6ig5zv) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/overview.adoc#L36)):*
> ```AsciiDoc
>   window.Polymer = {
>     dom: 'shadow'
>   }
> ```

Also semicolon here.

---

*[docs/tutorial/polymer.adoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBR6NSVHQO3hptPETt:-KXBR6NSVHQO3hptPETu:bq3g697) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/tutorial/polymer.adoc#L22)):*
> ```AsciiDoc
> 
>     <script>
>       // this script must run before Polymer is imported
> ```

Same here ^^^.

---

*[docs/tutorial/polymer.adoc, line 25 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBRK1BgI6jFmrY63sY:-KXBRK1BgI6jFmrY63sZ:b6ig5zv) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/tutorial/polymer.adoc#L25)):*
> ```AsciiDoc
>       window.Polymer = {
>         dom: 'shadow'
>       }
> ```

Also semicolon here.

---

*[docs/tutorial/polymer.adoc, line 80 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBPShxXjtAy7WPnQqd:-KXBPShxXjtAy7WPnQqe:ba795f1) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/tutorial/polymer.adoc#L80)):*
I feel like there should be a bit more information. Maybe:

> By default, Polymer uses shady DOM, which is not compatible with Angular. We created the Polymer global settings object and set it to use shadow DOM instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-:-KXBROr_ucjL7Djn2LTb:b-x5zs3h)*

**Comment by samiheikki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/ng-cli-webpack.adoc, line 102 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBR0Egf-l2A8youI8o:-KXElHfHWrj88YEqL2_8:b-896fix) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/ng-cli-webpack.adoc#L102)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Maybe try without this comment first?
</details>
Done.

---

*[docs/ng-cli-webpack.adoc, line 105 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBRAz7Pb9nb7rZVY0z:-KXElI-pMS7wIg3OWDn1:b-896fix) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/ng-cli-webpack.adoc#L105)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Although not required, it would be nice to have a semicolon here.
</details>
Done.

---

*[docs/overview.adoc, line 33 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBR3hASAxXoDXlreo4:-KXElIj3xwrajZF5LTxj:b-896fix) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/overview.adoc#L33)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Same here ^^^.
</details>
Done.

---

*[docs/overview.adoc, line 36 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBRHMoMhKQTiJXv7Nm:-KXElJ2CdN8pU96fNLpZ:b-896fix) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/overview.adoc#L36)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Also semicolon here.
</details>
Done.

---

*[docs/tutorial/polymer.adoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBR6NSVHQO3hptPETt:-KXElM0uaErHGBh9yKWG:b-896fix) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/tutorial/polymer.adoc#L22)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Same here ^^^.
</details>
Done.

---

*[docs/tutorial/polymer.adoc, line 25 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBRK1BgI6jFmrY63sY:-KXElLaIeeWcnjXTWcug:b-896fix) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/tutorial/polymer.adoc#L25)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Also semicolon here.
</details>
Done.

---

*[docs/tutorial/polymer.adoc, line 80 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-KXBPShxXjtAy7WPnQqd:-KXEmA6Q7c30Ozs_5THh:b-896fix) ([raw file](https://github.com/vaadin/angular2-polymer/blob/49822688ee35189dca29b24027f63dd728286886/docs/tutorial/polymer.adoc#L80)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> I feel like there should be a bit more information. Maybe:
> 
> > By default, Polymer uses shady DOM, which is not compatible with Angular. We created the Polymer global settings object and set it to use shadow DOM instead.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-:-KXEtmzoFWkIiTa7u4lJ:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/107#-:-KXFa1RNjHtZJbnG8ix6:bnfp4nl)*

**Pull request merged**
