### PR TITLE
Notify element for changes in object and array properties

### PR DESCRIPTION
**Pull request by manolo**
Connects to vaadin/components-team-tasks#132

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-ng2-polymer/1)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[polymer-element.ts, line 131 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqP1WEPKD57PHV4LD7:-KGqP1WEPKD57PHV4LD8:-1827566514) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L131)):_
We should not add this, it doesn't fix the issue if `items` is being set to a function after init.

---

_[polymer-element.ts, line 139 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqPv871EH8fWjsyI1w:-KGqPv88yQUTL8UiVH1v:-1829835414) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L139)):_
Instead add here `return { name: d.name, diff: diff || typeof this[d.name] === 'function' }` Diffs for functions return `null`, so let's always assign functions directly.

---

_[polymer-element.ts, line 142 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqQKlL_A_h93uJoTvq:-KGqQKlL_A_h93uJoTvr:683264517) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L142)):_
And here we should set `this._element[changes]` according to the type of `this[changes.name]` – for `array` we should use `slice(0)` and for Objects we should use `Object.assign` and for `function` just assign the value directly. Note that properties with primitive type don't get decorated with the `@Input` at all so we don't need to consider them here neither.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[polymer-element.ts, line 131 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqP1WEPKD57PHV4LD7:-KGr9yFDw-RS_KGOf_dQ:-499146009) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L131)):_
Done.

---

_[polymer-element.ts, line 139 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqPv871EH8fWjsyI1w:-KGr9zePJLuDZwfIVuqp:-499146009) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L139)):_
Done.

---

_[polymer-element.ts, line 142 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqQKlL_A_h93uJoTvq:-KGrA18S5P8tOLq1OAZ9:-1555840182) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L142)):_
Changed by element.notifyPath with this everything I've tested works and it should perform better since we don't make object copies each time something is modified

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by Saulis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[polymer-element.ts, line 142 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqQKlL_A_h93uJoTvq:-KGrsKRfZi7idemQFuJK:1728714513) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L142)):_
The copies are done intentionally, otherwise the observers are not called, see: https://github.com/Polymer/polymer/blob/1b02e96e77a0ef201976341fade763c617eca0d5/src/standard/notify-path.html#L97

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[polymer-element.ts, line 142 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqQKlL_A_h93uJoTvq:-KGuOX0h4Emh31HKDRTy:1290489694) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L142)):_
I already considered that, in fact my first approach was to check whether the object had changed, and I removed because notifyPath already does.
When angular changes an object we should pass the path changed, and not clone all the object, we only have to verify that angular and polymer follows the same convention, for instance i18n.today or items.0, otherwise we need to write a translator.
But definitively cloning objects and having different instances in the app could be more problematic than beneficial.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by Saulis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[polymer-element.ts, line 142 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqQKlL_A_h93uJoTvq:-KGuT1Rjm6XSCtzp8x7I:1767457459) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L142)):_
Sure cloning is a tradeoff, but I'm not sure if all the complexity added by making the notification more granular in this case is worth the effort. My worries come mostly from how the Angular diffing seems to work: for example to my knowledge the "diff" when setting a new array value isn't any different from a splice modification, which would mean that we would need to always need to iterate through the added/removed items and notify the Polymer element one item at a time. This would be hugely costly operation when applying new arrays.

You could try it out for comparison, but I'm a bit worried it won't be optimal either.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by Saulis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[polymer-element.ts, line 142 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqQKlL_A_h93uJoTvq:-KGuYVQe1ZEkFWzFhpiv:135492478) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L142)):_
Now that I thought about it, you're right – what we should do is first check if `this[changes.name]` is a different object from `element[changes.name]` and if it is, we will just assign it normally. If objects are the same, then we will use the diffs and notify each change separately. That should work perfectly.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[polymer-element.ts, line 142 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqQKlL_A_h93uJoTvq:-KGv--JEurifpTFRr_A4:-1809959127) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L142)):_
Actually we don't need that check because notifyPath already does the check and the assign.
The key here is just pass the correct path. 
Taking in account that we only consider right now first level object because we only visit properties, it should work in almost cases.
Anyway, we need to work better and check all the ng2 notification use cases to map to polymer.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[polymer-element.ts, line 142 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqQKlL_A_h93uJoTvq:-KHJIKRaCfwy96pgfNqK:2039790472) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L142)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Actually we don't need that check because notifyPath already does the check and the assign.
> The key here is just pass the correct path. 
> Taking in account that we only consider right now first level object because we only visit properties, it should work in almost cases.
> Anyway, we need to work better and check all the ng2 notification use cases to map to polymer.</details>
> We need to use the `forEach*` functions in the `KeyValueDiffer` https://github.com/angular/angular/blob/master/modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.ts to see which paths need to be notified.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[polymer-element.ts, line 142 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KGqQKlL_A_h93uJoTvq:-KHOEx_Yx-L4a-YIH5OG:-492046906) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/4d5652717a52d61f3a3ca75564ab4701122cee41/polymer-element.ts#L142)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> We need to use the `forEach*` functions in the `KeyValueDiffer` https://github.com/angular/angular/blob/master/modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.ts to see which paths need to be notified.</details>
> Yeah it's starting to look like the Angular 2 differs don't notice changes on deep properties like `expenses.0.value` 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by Saulis** [comment]
Still missing something for vaadin-charts, working on it.

**Comment by Saulis** [comment]
Had a chat with @alvarezguille – problem with the `vaadin-charts` currently is the `chart` object property inside the element that gets out of sync with the directive property. Main cause is that it gets changed inside the element but it doesn't have `notify: true`. Setting notifications on fixes the issue, alternative solution is to set the property to `readOnly` and ignore it in the directive.

**Comment by manolo** [comment]
@saulis  In your commits you broke grid because of functions not being consider anymore 

<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> Had a chat with @alvarezguille – problem with the `vaadin-charts` currently is the `chart` object property inside the element that gets out of sync with the directive property. Main cause is that it gets changed inside the element but it doesn't have `notify: true`. Setting notifications on fixes the issue, alternative solution is to set the property to `readOnly` and ignore it in the directive.</details>

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-:-KHQkEx1rzFkz5NOakn8:-1945612106)_

**Comment by manolo** [comment]
@saulis ignore my comment, I had something wrong, it's working fine

<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> @saulis  In your commits you broke grid because of functions not being consider anymore </details>

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-:-KHQlX9q2NdVC63A9IwS:251173562)_

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[polymer-element.js, line 150 [r5]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KHQpShojXIiebNFeqdW:-KHQpShpz8HSxKHM0TFf:-634589474) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/eccff2769eca6d348121b9da32dfbb32614d786a/polymer-element.js#L150)):_

> ``` JavaScript
>             }
>         },
>         ngDoCheck: function () {
> ```

I'm gonna give a shot simplifying things by using `ngOnChanges` instead of `ngDoCheck` 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[polymer-element.js, line 150 [r5]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KHQpShojXIiebNFeqdW:-KHQqNkjqmNZjeRNgYvX:-1899267274) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/eccff2769eca6d348121b9da32dfbb32614d786a/polymer-element.js#L150)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> I'm gonna give a shot simplifying things by using `ngOnChanges` instead of `ngDoCheck` </details>
> Not going to work, `ngOnChanges` isn't fired at all on sub-property changes.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[polymer-element.js, line 136 [r5]](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-KHTFpZC9BlNSttt_RVR:-KHTFpZC9BlNSttt_RVS:319385304) ([raw file](https://github.com/vaadin/vaadin-ng2-polymer/blob/eccff2769eca6d348121b9da32dfbb32614d786a/polymer-element.js#L136)):_

> ``` JavaScript
>             if (diff) {
>                 var elm = this._element;
>                 diff.forEachRemovedItem(function (item) { return elm.notifyPath(property + '.' + item.previousIndex); });
> ```

without passing the second argument, notifyPath does nothing. Sent a fix.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by manolo** [comment]
:lgtm: 

<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> @saulis ignore my comment, I had something wrong, it's working fine</details>

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1#-:-KHUs0wRZ-0nBFEKfxgx:980077423)_

**Comment by manolo** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-ng2-polymer/1)_

**Comment by manolo** [comment]
>  Main cause is that it gets changed inside the element but it doesn't have notify: true

@Saulis It seems that notify=true does not fixes the issue, it's fixed with readOnly=true, could be an issue

**Pull request merged**
