### PR TITLE
Upgrade to Angular v2.0.0-rc.6

### LINKED ISSUE #78: Incompatible with Angular2 rc.6
When using Angular2 Release Candidate 6, I'm not able to load my app, when including Polymer Components via `angular2-polymer`, because of the following error:

``` javascript
17:37:59.764 TypeError: core_1.provide is not a function
PolymerElement()main.bundle.js:71861
AppModule<()main.bundle.js:58569
<anonymous>main.bundle.js:58556
__webpack_require__()inline.js:53
<anonymous>main.bundle.js:58955
__webpack_require__()inline.js:53
<anonymous>main.bundle.js:34322
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask()polyfills.bundle.js:3277
Zone</Zone</Zone.prototype.runTask()polyfills.bundle.js:3177
ZoneTask/this.invoke()polyfills.bundle.js:3344
t/</<()localhost:4200:25
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask()polyfills.bundle.js:3277
Zone</Zone</Zone.prototype.runTask()polyfills.bundle.js:3177
ZoneTask/this.invoke()polyfills.bundle.js:3344
1main.bundle.js:71861:13
```

Probably because of [this](https://github.com/angular/angular/commit/bec5c5f#diff-8deabf0df78205f67c15546ad1410556L399) change in the Angular2 API.

This is the code, where the Error comes from:

``` javascript
import {NgModule, CUSTOM_ELEMENTS_SCHEMA}      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }  from './app.component';
import { MainComponent } from "./main/main.component";
import {PolymerElement} from "@vaadin/angular2-polymer";
import {routing} from "./app.routing";
import {ConfigFileApiConfigurationService} from "./shared/configuration/config-file-api-configuration.service";
import {API_CONFIGURATION_TOKEN} from "./shared/configuration/api-configuration";
import {HttpModule} from "@angular/http";

@NgModule({
  imports: [
    BrowserModule,
    routing,
    HttpModule
  ],
  declarations: [
    AppComponent,
    MainComponent,
    PolymerElement('paper-scroll-header-panel')
  ],
  providers: [
    {provide: API_CONFIGURATION_TOKEN, useClass: ConfigFileApiConfigurationService}
  ],
  schemas: [ CUSTOM_ELEMENTS_SCHEMA ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```

### PR DESCRIPTION
**Pull request by platosha**
Fixes #78
See also: https://github.com/vaadin/angular2-polymer-quickstart/pull/4

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/80)

### CODE REVIEW

**Comment by samiheikki** [comment]
Running the tests fails with this error message. (same errors at `npm install`)

`node_modules/@angular/forms/src/directives.d.ts(26,46): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/directives.d.ts(27,50): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/directives.d.ts(28,50): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/directives.d.ts(46,39): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/directives.d.ts(50,48): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.d.ts(12,18): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/form_providers.d.ts(13,38): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/form_providers.d.ts(18,47): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
src/polymer-element.ts(7,3): error TS2305: Module '"C:/Development/vaadin/angular2-polymer/node_modules/@angular/core/index"' has no exported member 'provide'.
src/polymer-element.ts(14,10): error TS2305: Module '"C:/Development/vaadin/angular2-polymer/node_modules/@angular/common/index"' has no exported member 'NgControl'.
src/polymer-element.ts(14,37): error TS2305: Module '"C:/Development/vaadin/angular2-polymer/node_modules/@angular/common/index"' has no exported member 'NG_VALUE_ACCESSOR'.
src/polymer-element.spec.ts(8,10): error TS2305: Module '"C:/Development/vaadin/angular2-polymer/node_modules/@angular/common/index"' has no exported member 'FORM_DIRECTIVES'.
src/polymer-element.spec.ts(8,27): error TS2305: Module '"C:/Development/vaadin/angular2-polymer/node_modules/@angular/common/index"' has no exported member 'ControlGroup'.
src/polymer-element.spec.ts(8,41): error TS2305: Module '"C:/Development/vaadin/angular2-polymer/node_modules/@angular/common/index"' has no exported member 'Control'.
src/polymer-element.spec.ts(345,3): error TS2345: Argument of type '{ directives: any[]; template: string; }' is not assignable to parameter of type 'ComponentMetadataType'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'ComponentMetadataType'.
npm ERR! Test failed.  See above for more details.
`

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/80#-:-KQy0NhXnjqElSHGl1Dk:b-9dc6zf)*

**Comment by samiheikki** [comment]
Running the tests fails with this error message. (same errors at npm install)

`typings/browser/ambient/es6-shim/index.d.ts(8,14): error TS2300: Duplicate identifier 'PropertyKey'.
typings/browser/ambient/es6-shim/index.d.ts(11,5): error TS2300: Duplicate identifier 'done'.
typings/browser/ambient/es6-shim/index.d.ts(12,5): error TS2300: Duplicate identifier 'value'.
typings/browser/ambient/es6-shim/index.d.ts(250,5): error TS2300: Duplicate identifier 'EPSILON'.
typings/browser/ambient/es6-shim/index.d.ts(285,5): error TS2300: Duplicate identifier 'MAX_SAFE_INTEGER'.
typings/browser/ambient/es6-shim/index.d.ts(292,5): error TS2300: Duplicate identifier 'MIN_SAFE_INTEGER'.
typings/browser/ambient/es6-shim/index.d.ts(348,5): error TS2300: Duplicate identifier 'flags'.
typings/browser/ambient/es6-shim/index.d.ts(500,5): error TS2300: Duplicate identifier 'prototype'.
typings/browser/ambient/es6-shim/index.d.ts(563,5): error TS2300: Duplicate identifier 'size'.
typings/browser/ambient/es6-shim/index.d.ts(572,5): error TS2300: Duplicate identifier 'prototype'.
typings/browser/ambient/es6-shim/index.d.ts(583,5): error TS2300: Duplicate identifier 'size'.
typings/browser/ambient/es6-shim/index.d.ts(592,5): error TS2300: Duplicate identifier 'prototype'.
typings/browser/ambient/es6-shim/index.d.ts(607,5): error TS2300: Duplicate identifier 'prototype'.
typings/browser/ambient/es6-shim/index.d.ts(621,5): error TS2300: Duplicate identifier 'prototype'.
typings/browser/ambient/jasmine/index.d.ts(44,5): error TS2300: Duplicate identifier 'fail'.
typings/browser/ambient/jasmine/index.d.ts(81,9): error TS2300: Duplicate identifier 'length'.
typings/browser/ambient/jasmine/index.d.ts(140,9): error TS2300: Duplicate identifier 'pass'.
typings/browser/ambient/jasmine/index.d.ts(141,9): error TS2300: Duplicate identifier 'message'.
typings/browser/ambient/jasmine/index.d.ts(151,9): error TS2300: Duplicate identifier 'setTimeout'.
typings/browser/ambient/jasmine/index.d.ts(152,9): error TS2300: Duplicate identifier 'clearTimeout'.
typings/browser/ambient/jasmine/index.d.ts(153,9): error TS2300: Duplicate identifier 'setInterval'.
typings/browser/ambient/jasmine/index.d.ts(154,9): error TS2300: Duplicate identifier 'clearInterval'.
typings/browser/ambient/jasmine/index.d.ts(155,9): error TS2300: Duplicate identifier 'updateInterval'.
typings/browser/ambient/jasmine/index.d.ts(157,9): error TS2300: Duplicate identifier 'currentSpec'.
typings/browser/ambient/jasmine/index.d.ts(159,9): error TS2300: Duplicate identifier 'matchersClass'.
typings/browser/ambient/jasmine/index.d.ts(205,9): error TS2300: Duplicate identifier 'type'.
typings/browser/ambient/jasmine/index.d.ts(209,9): error TS2300: Duplicate identifier 'description'.
typings/browser/ambient/jasmine/index.d.ts(211,9): error TS2300: Duplicate identifier 'totalCount'.
typings/browser/ambient/jasmine/index.d.ts(212,9): error TS2300: Duplicate identifier 'passedCount'.
typings/browser/ambient/jasmine/index.d.ts(213,9): error TS2300: Duplicate identifier 'failedCount'.
typings/browser/ambient/jasmine/index.d.ts(215,9): error TS2300: Duplicate identifier 'skipped'.
typings/browser/ambient/jasmine/index.d.ts(225,9): error TS2300: Duplicate identifier 'values'.
typings/browser/ambient/jasmine/index.d.ts(226,9): error TS2300: Duplicate identifier 'trace'.
typings/browser/ambient/jasmine/index.d.ts(230,9): error TS2300: Duplicate identifier 'matcherName'.
typings/browser/ambient/jasmine/index.d.ts(232,9): error TS2300: Duplicate identifier 'expected'.
typings/browser/ambient/jasmine/index.d.ts(233,9): error TS2300: Duplicate identifier 'actual'.
typings/browser/ambient/jasmine/index.d.ts(234,9): error TS2300: Duplicate identifier 'message'.
typings/browser/ambient/jasmine/index.d.ts(235,9): error TS2300: Duplicate identifier 'trace'.
typings/browser/ambient/jasmine/index.d.ts(239,9): error TS2300: Duplicate identifier 'name'.
typings/browser/ambient/jasmine/index.d.ts(240,9): error TS2300: Duplicate identifier 'message'.
typings/browser/ambient/jasmine/index.d.ts(241,9): error TS2300: Duplicate identifier 'stack'.
typings/browser/ambient/jasmine/index.d.ts(264,9): error TS2300: Duplicate identifier 'env'.
typings/browser/ambient/jasmine/index.d.ts(265,9): error TS2300: Duplicate identifier 'ensured'.
typings/browser/ambient/jasmine/index.d.ts(266,9): error TS2300: Duplicate identifier 'blocks'.
typings/browser/ambient/jasmine/index.d.ts(267,9): error TS2300: Duplicate identifier 'running'.
typings/browser/ambient/jasmine/index.d.ts(268,9): error TS2300: Duplicate identifier 'index'.
typings/browser/ambient/jasmine/index.d.ts(269,9): error TS2300: Duplicate identifier 'offset'.
typings/browser/ambient/jasmine/index.d.ts(270,9): error TS2300: Duplicate identifier 'abort'.
typings/browser/ambient/jasmine/index.d.ts(285,9): error TS2300: Duplicate identifier 'env'.
typings/browser/ambient/jasmine/index.d.ts(286,9): error TS2300: Duplicate identifier 'actual'.
typings/browser/ambient/jasmine/index.d.ts(287,9): error TS2300: Duplicate identifier 'spec'.
typings/browser/ambient/jasmine/index.d.ts(288,9): error TS2300: Duplicate identifier 'isNot'.
typings/browser/ambient/jasmine/index.d.ts(310,9): error TS2300: Duplicate identifier 'not'.
typings/browser/ambient/jasmine/index.d.ts(312,9): error TS2300: Duplicate identifier 'Any'.
typings/browser/ambient/jasmine/index.d.ts(351,9): error TS2300: Duplicate identifier 'id'.
typings/browser/ambient/jasmine/index.d.ts(352,9): error TS2300: Duplicate identifier 'env'.
typings/browser/ambient/jasmine/index.d.ts(353,9): error TS2300: Duplicate identifier 'description'.
typings/browser/ambient/jasmine/index.d.ts(354,9): error TS2300: Duplicate identifier 'queue'.
typings/browser/ambient/jasmine/index.d.ts(361,9): error TS2300: Duplicate identifier 'suite'.
typings/browser/ambient/jasmine/index.d.ts(363,9): error TS2300: Duplicate identifier 'afterCallbacks'.
typings/browser/ambient/jasmine/index.d.ts(364,9): error TS2300: Duplicate identifier 'spies_'.
typings/browser/ambient/jasmine/index.d.ts(366,9): error TS2300: Duplicate identifier 'results_'.
typings/browser/ambient/jasmine/index.d.ts(367,9): error TS2300: Duplicate identifier 'matchersClass'.
typings/browser/ambient/jasmine/index.d.ts(392,9): error TS2300: Duplicate identifier 'id'.
typings/browser/ambient/jasmine/index.d.ts(400,9): error TS2300: Duplicate identifier 'parentSuite'.
typings/browser/ambient/jasmine/index.d.ts(423,9): error TS2300: Duplicate identifier 'identity'.
typings/browser/ambient/jasmine/index.d.ts(424,9): error TS2300: Duplicate identifier 'and'.
typings/browser/ambient/jasmine/index.d.ts(425,9): error TS2300: Duplicate identifier 'calls'.
typings/browser/ambient/jasmine/index.d.ts(426,9): error TS2300: Duplicate identifier 'mostRecentCall'.
typings/browser/ambient/jasmine/index.d.ts(427,9): error TS2300: Duplicate identifier 'argsForCall'.
typings/browser/ambient/jasmine/index.d.ts(428,9): error TS2300: Duplicate identifier 'wasCalled'.
typings/browser/ambient/jasmine/index.d.ts(465,9): error TS2300: Duplicate identifier 'object'.
typings/browser/ambient/jasmine/index.d.ts(467,9): error TS2300: Duplicate identifier 'args'.
typings/browser/ambient/jasmine/index.d.ts(469,9): error TS2300: Duplicate identifier 'returnValue'.
typings/browser/ambient/jasmine/index.d.ts(482,9): error TS2300: Duplicate identifier 'started'.
typings/browser/ambient/jasmine/index.d.ts(483,9): error TS2300: Duplicate identifier 'finished'.
typings/browser/ambient/jasmine/index.d.ts(484,9): error TS2300: Duplicate identifier 'result'.
typings/browser/ambient/jasmine/index.d.ts(485,9): error TS2300: Duplicate identifier 'messages'.
typings/browser/ambient/jasmine/index.d.ts(499,9): error TS2300: Duplicate identifier 'Spec'.
typings/browser/ambient/jasmine/index.d.ts(500,9): error TS2300: Duplicate identifier 'clock'.
typings/browser/ambient/jasmine/index.d.ts(501,9): error TS2300: Duplicate identifier 'util'.
typings/globals/es6-shim/index.d.ts(3,14): error TS2300: Duplicate identifier 'PropertyKey'.
typings/globals/es6-shim/index.d.ts(6,5): error TS2300: Duplicate identifier 'done'.
typings/globals/es6-shim/index.d.ts(7,5): error TS2300: Duplicate identifier 'value'.
typings/globals/es6-shim/index.d.ts(245,5): error TS2300: Duplicate identifier 'EPSILON'.
typings/globals/es6-shim/index.d.ts(280,5): error TS2300: Duplicate identifier 'MAX_SAFE_INTEGER'.
typings/globals/es6-shim/index.d.ts(287,5): error TS2300: Duplicate identifier 'MIN_SAFE_INTEGER'.
typings/globals/es6-shim/index.d.ts(343,5): error TS2300: Duplicate identifier 'flags'.
typings/globals/es6-shim/index.d.ts(495,5): error TS2300: Duplicate identifier 'prototype'.
typings/globals/es6-shim/index.d.ts(558,5): error TS2300: Duplicate identifier 'size'.
typings/globals/es6-shim/index.d.ts(567,5): error TS2300: Duplicate identifier 'prototype'.
typings/globals/es6-shim/index.d.ts(578,5): error TS2300: Duplicate identifier 'size'.
typings/globals/es6-shim/index.d.ts(588,5): error TS2300: Duplicate identifier 'prototype'.
typings/globals/es6-shim/index.d.ts(603,5): error TS2300: Duplicate identifier 'prototype'.
typings/globals/es6-shim/index.d.ts(617,5): error TS2300: Duplicate identifier 'prototype'.
typings/globals/jasmine/index.d.ts(36,5): error TS2300: Duplicate identifier 'fail'.
typings/globals/jasmine/index.d.ts(73,9): error TS2300: Duplicate identifier 'length'.
typings/globals/jasmine/index.d.ts(74,9): error TS2375: Duplicate number index signature.
typings/globals/jasmine/index.d.ts(128,9): error TS2374: Duplicate string index signature.
typings/globals/jasmine/index.d.ts(132,9): error TS2300: Duplicate identifier 'pass'.
typings/globals/jasmine/index.d.ts(133,9): error TS2300: Duplicate identifier 'message'.
typings/globals/jasmine/index.d.ts(143,9): error TS2300: Duplicate identifier 'setTimeout'.
typings/globals/jasmine/index.d.ts(144,9): error TS2300: Duplicate identifier 'clearTimeout'.
typings/globals/jasmine/index.d.ts(145,9): error TS2300: Duplicate identifier 'setInterval'.
typings/globals/jasmine/index.d.ts(146,9): error TS2300: Duplicate identifier 'clearInterval'.
typings/globals/jasmine/index.d.ts(147,9): error TS2300: Duplicate identifier 'updateInterval'.
typings/globals/jasmine/index.d.ts(149,9): error TS2300: Duplicate identifier 'currentSpec'.
typings/globals/jasmine/index.d.ts(151,9): error TS2300: Duplicate identifier 'matchersClass'.
typings/globals/jasmine/index.d.ts(198,9): error TS2300: Duplicate identifier 'type'.
typings/globals/jasmine/index.d.ts(202,9): error TS2300: Duplicate identifier 'description'.
typings/globals/jasmine/index.d.ts(204,9): error TS2300: Duplicate identifier 'totalCount'.
typings/globals/jasmine/index.d.ts(205,9): error TS2300: Duplicate identifier 'passedCount'.
typings/globals/jasmine/index.d.ts(206,9): error TS2300: Duplicate identifier 'failedCount'.
typings/globals/jasmine/index.d.ts(208,9): error TS2300: Duplicate identifier 'skipped'.
typings/globals/jasmine/index.d.ts(218,9): error TS2300: Duplicate identifier 'values'.
typings/globals/jasmine/index.d.ts(219,9): error TS2300: Duplicate identifier 'trace'.
typings/globals/jasmine/index.d.ts(223,9): error TS2300: Duplicate identifier 'matcherName'.
typings/globals/jasmine/index.d.ts(225,9): error TS2300: Duplicate identifier 'expected'.
typings/globals/jasmine/index.d.ts(226,9): error TS2300: Duplicate identifier 'actual'.
typings/globals/jasmine/index.d.ts(227,9): error TS2300: Duplicate identifier 'message'.
typings/globals/jasmine/index.d.ts(228,9): error TS2300: Duplicate identifier 'trace'.
typings/globals/jasmine/index.d.ts(232,9): error TS2300: Duplicate identifier 'name'.
typings/globals/jasmine/index.d.ts(233,9): error TS2300: Duplicate identifier 'message'.
typings/globals/jasmine/index.d.ts(234,9): error TS2300: Duplicate identifier 'stack'.
typings/globals/jasmine/index.d.ts(257,9): error TS2300: Duplicate identifier 'env'.
typings/globals/jasmine/index.d.ts(258,9): error TS2300: Duplicate identifier 'ensured'.
typings/globals/jasmine/index.d.ts(259,9): error TS2300: Duplicate identifier 'blocks'.
typings/globals/jasmine/index.d.ts(260,9): error TS2300: Duplicate identifier 'running'.
typings/globals/jasmine/index.d.ts(261,9): error TS2300: Duplicate identifier 'index'.
typings/globals/jasmine/index.d.ts(262,9): error TS2300: Duplicate identifier 'offset'.
typings/globals/jasmine/index.d.ts(263,9): error TS2300: Duplicate identifier 'abort'.
typings/globals/jasmine/index.d.ts(278,9): error TS2300: Duplicate identifier 'env'.
typings/globals/jasmine/index.d.ts(279,9): error TS2300: Duplicate identifier 'actual'.
typings/globals/jasmine/index.d.ts(280,9): error TS2300: Duplicate identifier 'spec'.
typings/globals/jasmine/index.d.ts(281,9): error TS2300: Duplicate identifier 'isNot'.
typings/globals/jasmine/index.d.ts(303,9): error TS2300: Duplicate identifier 'not'.
typings/globals/jasmine/index.d.ts(305,9): error TS2300: Duplicate identifier 'Any'.
typings/globals/jasmine/index.d.ts(344,9): error TS2300: Duplicate identifier 'id'.
typings/globals/jasmine/index.d.ts(345,9): error TS2300: Duplicate identifier 'env'.
typings/globals/jasmine/index.d.ts(346,9): error TS2300: Duplicate identifier 'description'.
typings/globals/jasmine/index.d.ts(347,9): error TS2300: Duplicate identifier 'queue'.
typings/globals/jasmine/index.d.ts(354,9): error TS2300: Duplicate identifier 'suite'.
typings/globals/jasmine/index.d.ts(356,9): error TS2300: Duplicate identifier 'afterCallbacks'.
typings/globals/jasmine/index.d.ts(357,9): error TS2300: Duplicate identifier 'spies_'.
typings/globals/jasmine/index.d.ts(359,9): error TS2300: Duplicate identifier 'results_'.
typings/globals/jasmine/index.d.ts(360,9): error TS2300: Duplicate identifier 'matchersClass'.
typings/globals/jasmine/index.d.ts(385,9): error TS2300: Duplicate identifier 'id'.
typings/globals/jasmine/index.d.ts(393,9): error TS2300: Duplicate identifier 'parentSuite'.
typings/globals/jasmine/index.d.ts(416,9): error TS2300: Duplicate identifier 'identity'.
typings/globals/jasmine/index.d.ts(417,9): error TS2300: Duplicate identifier 'and'.
typings/globals/jasmine/index.d.ts(418,9): error TS2300: Duplicate identifier 'calls'.
typings/globals/jasmine/index.d.ts(419,9): error TS2300: Duplicate identifier 'mostRecentCall'.
typings/globals/jasmine/index.d.ts(420,9): error TS2300: Duplicate identifier 'argsForCall'.
typings/globals/jasmine/index.d.ts(421,9): error TS2300: Duplicate identifier 'wasCalled'.
typings/globals/jasmine/index.d.ts(460,9): error TS2300: Duplicate identifier 'object'.
typings/globals/jasmine/index.d.ts(462,9): error TS2300: Duplicate identifier 'args'.
typings/globals/jasmine/index.d.ts(464,9): error TS2300: Duplicate identifier 'returnValue'.
typings/globals/jasmine/index.d.ts(477,9): error TS2300: Duplicate identifier 'started'.
typings/globals/jasmine/index.d.ts(478,9): error TS2300: Duplicate identifier 'finished'.
typings/globals/jasmine/index.d.ts(479,9): error TS2300: Duplicate identifier 'result'.
typings/globals/jasmine/index.d.ts(480,9): error TS2300: Duplicate identifier 'messages'.
typings/globals/jasmine/index.d.ts(494,9): error TS2300: Duplicate identifier 'Spec'.
typings/globals/jasmine/index.d.ts(495,9): error TS2300: Duplicate identifier 'clock'.
typings/globals/jasmine/index.d.ts(496,9): error TS2300: Duplicate identifier 'util'.
npm ERR! Test failed.  See above for more details.`

**Comment by platosha** [comment]
Please try removing the `typings` directory.

**Comment by samiheikki** [comment]
Works, Thanks @platosha

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/80#-:-KQyOEGurTjdCl6SIyW9:bnfp4nl)_

**Pull request merged**
