### PR TITLE
Remove Polymer.dom.flush() call after each DOM operation

### LINKED ISSUE #34: Parent polymer elements dont seem to react to change in children.
**tldr:** When children of paper-dropdown-menu are updated by Angular, the parent does not reload or react to the change. The "selected" option does not bind to the new items, for example, unless we  update it as well. **The example code is available here: https://github.com/dirtysanchez69/issue-angular2-polymer**

Say I have a paper-dropdown-menu, as such (this works fine):

```
//hardcoded options and selection

<paper-dropdown-menu label="hardcoded options and selection">
  <paper-listbox 
  [selected]="1"
  class="dropdown-content">
    <paper-item *ngFor="let option of ['hi', 'hello', 'yo']">{{option}}</paper-item>
  </paper-listbox>
</paper-dropdown-menu>
```

In this case, the child (paper-item) is presumably parsed before the parent (paper-listbox), and the parent selects the second of its children to be the selected value.

Now, if the options arrive a bit later, after an async event, the options (paper-items) are updated just fine, but we lose the selected value.

```
//hardcoded selection

<paper-dropdown-menu label="hardcoded selection">
  <paper-listbox 
  [selected]="1"
  class="dropdown-content">
    <paper-item *ngFor="let option of dropdownOptions.fruit">{{option}}</paper-item>
  </paper-listbox>
</paper-dropdown-menu>
```

If dropdownOptions.fruit is initialized with some values, we see the selected value, but upon updating them, the selected value disappears.

Now, if we also bind the selected value, and we update that as well upon receiving the new data, then the new selected value is displayed (hooray). However, this only works if we actually change the value of the "selected" property. If we initialize this value to 1, then we must pick another number in order to trigger the update (which still leaves us with a problem).

```
<paper-dropdown-menu label="selection refresh" #fruitDropdown >
  <paper-listbox 
  [selected]="userData.fruitSelection"
  class="dropdown-content">
    <paper-item *ngFor="let option of dropdownOptions.fruit">{{option}}</paper-item>
  </paper-listbox>
</paper-dropdown-menu>
```

snap 2016-06-28 at 02 03 16

What do you think of this?
Is there a clean way to forcibly trigger a reload on a polymer element?

### PR DESCRIPTION
**Pull request by platosha**
Fixes #34

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/39)

### CODE REVIEW

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/39#-:-KL_Wkm4idf9gzRofAYN:1417088721)_

**Comment by tomivirkki** [comment]
Should there also be a new test for the case described in the original issue #34?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[src/test-element.html, line 12 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/39#-KLq0qggxZPQRbTo-j75:-KLq0qghYge3dh7VUYuB:2068134308) ([raw file](https://github.com/vaadin/angular2-polymer/blob/0373b126827d51880ade02a39f3c4df66d96ee86/src/test-element.html#L12)):_

> ``` HTML
>     <div id="all">
>       <content></content>
>     </div>
> ```

These two slots were here to make sure that the nodes distribute correctly. Now they end up under the same parent node so the tests are no longer valid.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/39#-:-KLq0A4uwg_IAQicY5C4:676240913)_

**Comment by platosha** [comment]
@tomivirkki good point. Will try to add the test.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/test-element.html, line 12 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/39#-KLq0qggxZPQRbTo-j75:-KLq1qUEByIcYRus6ipS:2140772215) ([raw file](https://github.com/vaadin/angular2-polymer/blob/0373b126827d51880ade02a39f3c4df66d96ee86/src/test-element.html#L12)):_
<details><summary>

<i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>



> These two slots were here to make sure that the nodes distribute correctly. Now they end up under the same parent node so the tests are no longer valid.
> </details>
> The tests were also changed to retrieve nodes from Polymer’s logic DOM tree, i.e. with `Polymer.dom(contentNode).getDistributedNodes()`.

My idea: we should rather care about the logic tree, instead of the real one. We should not test how Polymer distributes nodes, but rather that Polymer knows where to distribute them.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/39#-:-KLq2YTMhw1b9XqGyX-S:1155447961)_

**Comment by platosha** [comment]
Added the test for the issue #34 cause.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/39#-:-KLqDmXwX_Rgbf7k2Pbj:-1614371928)_

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/39#-:-KLuEoo9IRImk3Tb9TOo:1417088721)_

**Pull request merged**
