### PR TITLE
Prepare doc to publish in website

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/components-team-tasks/issues/205

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/88)

### CODE REVIEW

**Comment by samiheikki** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[docs/ng-cli-webpack.adoc, line 18 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-KRh-Wnnz6d_RIEWFFiO:-KRh-WnoGDLmaom52bZK:btcptuf) ([raw file](https://github.com/vaadin/angular2-polymer/blob/b00b9cac27f139aeaf285eaf629e07e9fb31d8cf/docs/ng-cli-webpack.adoc#L18)):_

> ``` AsciiDoc
> In this document we will describe all the modifications you have to make to your Angular CLI project to use Polymer elements.
> 
> [[vaadin-angular2-polymer.ng2cliwebpack.sysjs-note]]
> ```

Could this be systemjs-note? webpack isn't abbreviated either.

---

_[docs/ng-cli-webpack.adoc, line 118 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-KRhKi8FjUwvKeVwHYV_:-KRhKi8G-UUmsYwj0BRd:ba96jpq) ([raw file](https://github.com/vaadin/angular2-polymer/blob/b00b9cac27f139aeaf285eaf629e07e9fb31d8cf/docs/ng-cli-webpack.adoc#L118)):_

> ``` AsciiDoc
> ----
> 
> Finally, change the main entry point of the application to load the new loader script. Edit the [filename]#angular-cli.json# file in the project root and  replace the line `"main": "main.ts",` with  `"main": "main-polymer.ts",`.
> ```

Can you change `Finally` word to something more appropriate?  There are still few chapters remaining and in there we use the word `finally`.

---

_[docs/ng-cli.adoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-KRhLn1dJNFBzdUTUvba:-KRhLn1eOuQMgercwhss:b-wr55w4) ([raw file](https://github.com/vaadin/angular2-polymer/blob/b00b9cac27f139aeaf285eaf629e07e9fb31d8cf/docs/ng-cli.adoc#L21)):_

> ``` AsciiDoc
> .Note for the Angular CLI Webpack Version Users
> ====
> If you are using the webpack version of the Angular CLI tool, please use the link:ng-cli-webpack.adoc[Using Polymer Elements in Angular CLI Webpack Applications] guide.
> ```

Can you remove `Applications` word? The title of the other page is now just `Using in Angular CLI Webpack`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88)_

**Comment by platosha** [comment]
I think, it’s better to publish the webpack guide instead of the SystemJS one, rather then in addition to.

Looks like `npm install -g angular-cli` installs the webpack version, currently. Also, in the latest angular-cli version number (1.0.0-beta.14), the -webpack suffix was dropped.

The other guide is not needed that much anymore. We can remove the docs webside data header from the old guide, and the cross references between them.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-:-KRhQfnYL_BNPOByib7U:b-7d6nf1)_

**Comment by manolo** [comment]
the systemjs guide include how to deal with karma tests shouldn't we add that to the webpack guide ? 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-:-KRhdfZP6bAztgGfYApS:b-wyyjda)_

**Comment by platosha** [comment]
@manolo the tests worked for me, those instructions were not required by the time I wrote the webpack guide. Please try if they still work. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-:-KRhkknSn33Ud60uRwfg:b-wzdfwv)_

**Comment by manolo** [comment]
@platosha  When I run `ng test` after adding polymer elements I get these errors in console:

```
Chrome 52.0.2743 (Mac OS X 10.11.5) App: MyProject should create the app FAILED
    Can't bind to 'label' since it isn't a known property of 'vaadin-combo-box'.
    1. If 'vaadin-combo-box' is an Angular component and it has 'label' input, then verify that it is part of this module.
    2. If 'vaadin-combo-box' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
...
...
```

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-:-KRiaREQc_dWILg7PIOW:b-k6qtdv)_

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[docs/ng-cli-webpack.adoc, line 18 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-KRh-Wnnz6d_RIEWFFiO:-KRmxgk71Kx-OpLlfFOg:b-896fix) ([raw file](https://github.com/vaadin/angular2-polymer/blob/b00b9cac27f139aeaf285eaf629e07e9fb31d8cf/docs/ng-cli-webpack.adoc#L18)):_
<details><summary>

<i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>



> Could this be systemjs-note? webpack isn't abbreviated either.
> </details>
> Done.

---

_[docs/ng-cli-webpack.adoc, line 118 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-KRhKi8FjUwvKeVwHYV_:-KRmxhzV4E6nkFIIM-Kl:b-896fix) ([raw file](https://github.com/vaadin/angular2-polymer/blob/b00b9cac27f139aeaf285eaf629e07e9fb31d8cf/docs/ng-cli-webpack.adoc#L118)):_
<details><summary>

<i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>



> Can you change `Finally` word to something more appropriate?  There are still few chapters remaining and in there we use the word `finally`.
> </details>
> Done.

---

_[docs/ng-cli.adoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-KRhLn1dJNFBzdUTUvba:-KRmxuXypWHv1jDIvPfO:bnqj90s) ([raw file](https://github.com/vaadin/angular2-polymer/blob/b00b9cac27f139aeaf285eaf629e07e9fb31d8cf/docs/ng-cli.adoc#L21)):_
<details><summary>

<i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>



> Can you remove `Applications` word? The title of the other page is now just `Using in Angular CLI Webpack`
> </details>
> Removed this fil

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88)_

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

_[docs/ng-cli-webpack.adoc, line 312 at r3](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-KS0FRTCXA4XL7N8pFhJ:-KS0FRTCXA4XL7N8pFhK:b5m9qv2) ([raw file](https://github.com/vaadin/angular2-polymer/blob/ab29e3001bb17120a57fd30983b254d6a9625251/docs/ng-cli-webpack.adoc#L312)):_

> ``` AsciiDoc
> ----
> 
> === Testing Polymer Elements
> ```

I would leave this chapter out. The text itself says this is discouraged and should not be done..

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88)_

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

_[docs/ng-cli-webpack.adoc, line 312 at r3](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-KS0FRTCXA4XL7N8pFhJ:-KS0vaasVRAtSPxNZDxD:b-896fix) ([raw file](https://github.com/vaadin/angular2-polymer/blob/ab29e3001bb17120a57fd30983b254d6a9625251/docs/ng-cli-webpack.adoc#L312)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> I would leave this chapter out. The text itself says this is discouraged and should not be done..
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88)_

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/88#-:-KS1NCe4LCBP5FXoErue:bnfp4nl)_

**Pull request merged**
