### PR TITLE
Replace LightDomObserverDirective with PolymerDomAdapter

### LINKED ISSUE #9: Make Angular 2 to use Polymer.dom accesors

### PR DESCRIPTION
**Pull request by platosha**
Fixes #9

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/12)

### CODE REVIEW

**Comment by manolo** [comment]
The approach is working to me. Good job!

I miss a couple of tests though.

<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> #### Replace LightDomObserverDirective with PolymerDomAdapter
> 
> Fixes #9
> 
> </details>

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/polymer-element.ts, line 28 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-KIfcbRX62e-AEYk99Uw:-KIfcbRX62e-AEYk99Ux:-1866716711) ([raw file](https://github.com/vaadin/angular2-polymer/blob/508fbed3239e0dfe30864eb9b8489e164a8d7ffd/src/polymer-element.ts#L28)):_

> ``` XML
> }
> 
> class PolymerShadyDomAdapter extends PolymerDomAdapter {
> ```

Is there a good reason for not using the same class adapter in both cases. Polymer.dom already should know when it's running in a shady or shadow env.

---

_[src/polymer-element.ts, line 59 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-KIfcqXF179OwGAawc_x:-KIfcqXF179OwGAawc_y:-967367199) ([raw file](https://github.com/vaadin/angular2-polymer/blob/508fbed3239e0dfe30864eb9b8489e164a8d7ffd/src/polymer-element.ts#L59)):_

> ``` XML
> 
>   setAttribute(el, name, value) { Polymer.dom(el).setAttribute(name, value); }
>   removeAttribute(el, name) { Polymer.dom(el).removeAttribute(name); }
> ```

All those overrides seems very repetitive, I'm wondering if we can walk on all prototype function properties and override the implementation in a loop.

---

_[src/polymer-element.ts, line 293 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-KIfdCg4FMzMBKGncIxG:-KIfdCg4FMzMBKGncIxH:-1463905898) ([raw file](https://github.com/vaadin/angular2-polymer/blob/508fbed3239e0dfe30864eb9b8489e164a8d7ffd/src/polymer-element.ts#L293)):_

> ``` XML
>   });
> 
>   var directives = [changeEventsAdapterDirective, notifyForDiffersDirective, chartsConfigurationDirective];
> ```

Why do you change the name. I see this name so much coupled to a vaadin product. I'd rather the old name

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-:-KIfdOJoF7_xge5irNm4:-2144871112)_

**Comment by tomivirkki** [comment]
You can now uncomment the (previously not working) expectation from polymer-element.spec.ts ("should support ngif")

<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> The approach is working to me. Good job!
> 
> I miss a couple of tests though.
> </details>

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-:-KIfmevsL4ds5oujSncp:1531029838)_

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/polymer-element.ts, line 28 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-KIfcbRX62e-AEYk99Uw:-KIfiWIuTaHNcIMANn6o:1513204295) ([raw file](https://github.com/vaadin/angular2-polymer/blob/508fbed3239e0dfe30864eb9b8489e164a8d7ffd/src/polymer-element.ts#L28)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Is there a good reason for not using the same class adapter in both cases. Polymer.dom already should know when it's running in a shady or shadow env.
> </details>
> This works, but it's redundant to proxy all the dom calls through Polymer.dom in case of the shadow env. Performance overhead for no benefits.

---

_[src/polymer-element.ts, line 59 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-KIfcqXF179OwGAawc_x:-KIfjQQS87FRO7481Zth:-2000322549) ([raw file](https://github.com/vaadin/angular2-polymer/blob/508fbed3239e0dfe30864eb9b8489e164a8d7ffd/src/polymer-element.ts#L59)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> All those overrides seems very repetitive, I'm wondering if we can walk on all prototype function properties and override the implementation in a loop.
> </details>
> I don't think it's a good idea here. The implementations look similar at first, but there are some differences:
- Some methods do return value, some do not
- Some methods call another overridden method instead of `Polymer.dom(el)`, for ex.: `addClass` calls `classList`
- Traversal methods (e.g., `firstChild`) are mapped to properties, not calls. In case if `parentElement` method the name of the method and the mapped property do not match
- Modification methods (e.g., `appendChild`) are complex:
  - They flush the DOM after the operation explicitly. Though this might be not required. We need more testing here.
  - The parameters order do not match in case of `insertBefore`, `insertAfter`, `insertAllBefore`.
  - `insertAllBefore` requires iterating in the implementation.

There are a lot of moments when we need to know more than just a name to build a correct implementation for a method. For that reason, I think, the plain method overrides are easier to understand and maintain, than an obscure iteration.

---

_[src/polymer-element.ts, line 293 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-KIfdCg4FMzMBKGncIxG:-KIfvAxLlmN2oORmFGGz:-1664751658) ([raw file](https://github.com/vaadin/angular2-polymer/blob/508fbed3239e0dfe30864eb9b8489e164a8d7ffd/src/polymer-element.ts#L293)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Why do you change the name. I see this name so much coupled to a vaadin product. I'd rather the old name
> </details>
> The old name doesn't make sense anymore, since the lightDomObserver has been removed.

The new name reflects the purpose of this directive. It's needed especially for the charts, and nothing else.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12)_

**Comment by platosha** [comment]
@tomivirkki Done. Thanks for the suggestion.

<details><summary>

<i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>



> You can now uncomment the (previously not working) expectation from polymer-element.spec.ts ("should support ngif")
> </details>

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-:-KIfwJA805hkTbWxSJr4:-1784468699)_

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/polymer-element.ts, line 28 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-KIfcbRX62e-AEYk99Uw:-KIg4FsObCi51pfXV0BI:-534552754) ([raw file](https://github.com/vaadin/angular2-polymer/blob/508fbed3239e0dfe30864eb9b8489e164a8d7ffd/src/polymer-element.ts#L28)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> This works, but it's redundant to proxy all the dom calls through Polymer.dom in case of the shadow env. Performance overhead for no benefits.
> </details>
> Shouldn't polymer dom take care of performance already?
> I don't see the need of this directive knowing about the fact of shady/shadow, which btw could change in the future.

---

_[src/polymer-element.ts, line 293 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-KIfdCg4FMzMBKGncIxG:-KIg2zwY2cj33tEdG65X:-1319236052) ([raw file](https://github.com/vaadin/angular2-polymer/blob/508fbed3239e0dfe30864eb9b8489e164a8d7ffd/src/polymer-element.ts#L293)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> The old name doesn't make sense anymore, since the lightDomObserver has been removed.
> 
> The new name reflects the purpose of this directive. It's needed especially for the charts, and nothing else.
> </details>
> Could be renamed to something not including the product name?
> Maybe isInitializedDirective or hasInitializerDirective

Also we could consider to push the charts directive if the native element contains isInitialized and reloadConfiguration

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12)_

**Comment by platosha** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/polymer-element.ts, line 28 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-KIfcbRX62e-AEYk99Uw:-KIg8sMEDBjuQ7IXs9mV:-105530508) ([raw file](https://github.com/vaadin/angular2-polymer/blob/508fbed3239e0dfe30864eb9b8489e164a8d7ffd/src/polymer-element.ts#L28)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Shouldn't polymer dom take care of performance already?
> I don't see the need of this directive knowing about the fact of shady/shadow, which btw could change in the future.
> </details>
> Polymer DOM API is required only for the Shady DOM. In case of the Shadow DOM mode, this becomes a redundant proxy wrapper on top of the browser API. Why to call Polymer.dom methods then? They do nothing useful for this case.

At the same time, invoking these proxy methods each single time when Angular needs to access DOM does have a performance impact. Isn't it good to avoid these unnecessary JS calls?

Polymer process these settings on load time. Actually it’s hardly even possible to switch modes after Polymer is loaded, thus we are safe to consider `Polymer.Settings.useShadow` as a constant here. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12)_

**Comment by platosha** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/polymer-element.ts, line 293 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-KIfdCg4FMzMBKGncIxG:-KIgGUe0GBYMZFELH6LL:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/508fbed3239e0dfe30864eb9b8489e164a8d7ffd/src/polymer-element.ts#L293)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Could be renamed to something not including the product name?
> Maybe isInitializedDirective or hasInitializerDirective
> 
> Also we could consider to push the charts directive if the native element contains isInitialized and reloadConfiguration
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12)_

**Comment by manolo** [comment]
:lgtm:

<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> @tomivirkki Done. Thanks for the suggestion.
> </details>

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/12#-:-KImD6cMf2XJKHa_yKHF:1417088721)_

**Pull request merged**
