### PR TITLE
Adding API document

### PR DESCRIPTION
**Pull request by manolo**
Connected to #10 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/16)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[docs/api.adoc, line 9 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4b6wZveWH5ZvvqQfT:-KJ4b6wZveWH5ZvvqQfU:-1275200114) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L9)):_

> ``` AsciiDoc
> == Introduction
> 
> This module consists on one generic Angular 2 directive named [classname]#PolymerElement# which is able to handle any Polymer element for easy integrating on Angular apps.
> ```

“...consists _of_ one generic Angular 2 _directives factory method_ named PolymerElement, which is...”. Note the comma before “which”.

---

_[docs/api.adoc, line 13 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4bXZuqTgr2j5X_MDT:-KJ4bXZuqTgr2j5X_MDU:-1037963916) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L13)):_

> ``` AsciiDoc
> == Features
> 
> The [classname]#PolymerElement# directive is composed by a set of low level directives which would be added to the component dynamically.
> ```

Strictly speaking, The PolymerElement is not a directive but a factory, that returns a set of directives.

I think, “composed of” or “composed from” would sound better.

---

_[docs/api.adoc, line 16 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4dRelETa39msrdmwA:-KJ4dRelETa39msrdmwB:2120919582) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L16)):_

> ``` AsciiDoc
> 
> `changeEventsAdapterDirective`::
> This directive configures any public and notifiable [propertyname]#property# in a Polymer element to be an Angular 2 link:https://angular.io/docs/js/latest/api/core/DirectiveMetadata-class.html#!#outputs-anchor[output].
> ```

Configures all the public properties that notify for their value change. “Notifiable” sounds like the property can receive notify, but actually it can produce a notify

---

_[docs/api.adoc, line 22 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4gTcnB4F5T_5XMwir:-KJ4gTcoOyI5eNBwsSJf:314291147) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L22)):_

> ``` AsciiDoc
> Configures all public [propertyname]#properties# in a Polymer element to be an Angular 2 link:https://angular.io/docs/js/latest/api/core/DirectiveMetadata-class.html#!#inputs-anchor[input].
> It allows to notify changes from the Angular side to Polymer. It supports primitive types, as well as both Array and Object properties, but not it's children.
> If you want to notify nested object changes, you can still do it by calling the Polymer's [methodname]#notifyPath# method on the native element.
> ```

“on the native element” is confusing: Polymer elements are not native, they are custom. “On the element”, maybe?

---

_[docs/api.adoc, line 25 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4glhGCjHnvY5IlxRH:-KJ4glhGCjHnvY5IlxRI:-1130406074) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L25)):_

> ``` AsciiDoc
> 
> `formElementDirective`::
> If the element has the Polymer Form Behavior, this directive is added to the component, and configures it to have a form control in Angular 2.
> ```

“Form _Element_ Behavior”, or namely “IronFormElementBehavior”.

Maybe say: “to be compatible with ngForm”?

---

_[docs/api.adoc, line 28 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4hiTQimDn921g64wA:-KJ4hiTQimDn921g64wB:-771360845) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L28)):_

> ``` AsciiDoc
> 
> `validationDirective`::
> It is another directive added in the case of the element has the Polymer Form behavior. It forwards Angular checks to Polymer validations.
> ```

Actually it updates the “invalid” property of the Polymer element (declared in `Polymer.IronValidatableBehavior`) using the `ngControl` state and validity.

---

_[docs/api.adoc, line 36 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4ngM-LRA_snLR4o7J:-KJ4ngM-LRA_snLR4o7K:-460018149) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L36)):_

> ``` AsciiDoc
> == Usage
> 
> Previously to use the [classname]#PolymerElement# in the [propertyname]#directives# block of your [classname]#Component#, you have to import it as is shown in the example below.
> ```

Previously is confusing here. What has changed since then? Let’s put: “In order to use” instead.

---

_[docs/api.adoc, line 39 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4o8g4oeyxux2KT56S:-KJ4o8g4oeyxux2KT56T:1172381760) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L39)):_

> ``` AsciiDoc
> 
> The only public API is the [classname]#PolymerElement(tagName: string): Array<Directive># factory method.
> The argument [propertyname]#tagName# is mandatory, and must match the tag name of the Polymer element to wrap.
> ```

“of the Polymer element.” I’d drop “to wrap”, directives don't wrap elements, they are attached to elements.

---

_[docs/api.adoc, line 41 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4plIfJGl17WOwBZ0q:-KJ4plIg3yddZnYbRy9T:573040702) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L41)):_

> ``` AsciiDoc
> The argument [propertyname]#tagName# is mandatory, and must match the tag name of the Polymer element to wrap.
> Hence, you have to add the [classname]#PolymerElement# directive as many times as different Polymer elements you are using in your Angular 2 component.
> It returns the set of directives necessary for the given Polymer element.
> ```

Maybe: “Each time it returns the set...”, to make it sound closer to the previous sentence.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16)_

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[docs/api.adoc, line 9 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4b6wZveWH5ZvvqQfT:-KJ4rM-xnslWWiqEkIQ1:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L9)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> “...consists _of_ one generic Angular 2 _directives factory method_ named PolymerElement, which is...”. Note the comma before “which”.
> </details>
> Done.

---

_[docs/api.adoc, line 13 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4bXZuqTgr2j5X_MDT:-KJ4s55A0apJO1BQF2jF:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L13)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Strictly speaking, The PolymerElement is not a directive but a factory, that returns a set of directives.
> 
> I think, “composed of” or “composed from” would sound better.
> </details>
> Done.

---

_[docs/api.adoc, line 16 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4dRelETa39msrdmwA:-KJ4sbRSAnZzVE07C6nu:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L16)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Configures all the public properties that notify for their value change. “Notifiable” sounds like the property can receive notify, but actually it can produce a notify
> </details>
> Done.

---

_[docs/api.adoc, line 22 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4gTcnB4F5T_5XMwir:-KJ4siYDRwElZflnW1Pr:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L22)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> “on the native element” is confusing: Polymer elements are not native, they are custom. “On the element”, maybe?
> </details>
> Done.

---

_[docs/api.adoc, line 25 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4glhGCjHnvY5IlxRH:-KJ4tI8zbbZib8mHjETp:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L25)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> “Form _Element_ Behavior”, or namely “IronFormElementBehavior”.
> 
> Maybe say: “to be compatible with ngForm”?
> </details>
> Done.

---

_[docs/api.adoc, line 28 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4hiTQimDn921g64wA:-KJ4usTaNIpCpCZaL0s4:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L28)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Actually it updates the “invalid” property of the Polymer element (declared in `Polymer.IronValidatableBehavior`) using the `ngControl` state and validity.
> </details>
> Done.

---

_[docs/api.adoc, line 36 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4ngM-LRA_snLR4o7J:-KJ4uzJGyzQZnldfVTs1:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L36)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Previously is confusing here. What has changed since then? Let’s put: “In order to use” instead.
> </details>
> Done.

---

_[docs/api.adoc, line 39 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4o8g4oeyxux2KT56S:-KJ4v9vkJCbgib8uVvSQ:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L39)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> “of the Polymer element.” I’d drop “to wrap”, directives don't wrap elements, they are attached to elements.
> </details>
> Done.

---

_[docs/api.adoc, line 41 [r2]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ4plIfJGl17WOwBZ0q:-KJ4vu4NwFVuI1b3wRq5:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/a5b02e0e1b4f5b4eb0fc3672b8eecc86fb7c8ce0/docs/api.adoc#L41)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Maybe: “Each time it returns the set...”, to make it sound closer to the previous sentence.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16)_

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[docs/api.adoc, line 16 [r3]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ5HG9SMGd8_XuBq1-z:-KJ5HG9TIynVeFbAa3I3:-469308554) ([raw file](https://github.com/vaadin/angular2-polymer/blob/1f526ae290eb3ca74d9f7c376c586871f6ebf3c3/docs/api.adoc#L16)):_

> ``` AsciiDoc
> 
> `changeEventsAdapterDirective`::
> This directive configures all the public [propertyname]#property#, that notify for their value change in a Polymer element, to be an Angular 2 link:https://angular.io/docs/js/latest/api/core/DirectiveMetadata-class.html#!#outputs-anchor[output].
> ```

“all the public _properties_”, the plural noun should be used here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16)_

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[docs/api.adoc, line 16 [r3]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJ5HG9SMGd8_XuBq1-z:-KJ5uBf6NlOD1dRrtUt3:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/1f526ae290eb3ca74d9f7c376c586871f6ebf3c3/docs/api.adoc#L16)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> “all the public _properties_”, the plural noun should be used here.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16)_

**Comment by platosha** [comment]
:lgtm:

<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> #### Adding API document
> 
> Connected to #10 
> 
> </details>

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-:-KJ64L0yC8OJ2KK1a8Gn:1417088721)_

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[docs/api.adoc, line 13 [r5]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJF4BkHp1cT6TvBYTha:-KJF4BkIM-pzpYMG8eaq:-49245785) ([raw file](https://github.com/vaadin/angular2-polymer/blob/69ca6596ab9f1a7c342978f8bd61be4d0f64ad8a/docs/api.adoc#L13)):_

> ``` AsciiDoc
> 
> [[vaadin-angular2-polymer.api.introduction]]
> == Introduction
> ```

Sorry, mislooked this yesterday.

The previous paragraph looks very poor and doesn't really explain what is inside. At the same time, really nice explanation is given in the “Introduction“ section.

Maybe remove the paragraph saying “Native Angular 2 directive for Polymer.” and the “Introduction” section title?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16)_

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16)_

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[docs/api.adoc, line 13 [r5]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16#-KJF4BkHp1cT6TvBYTha:-KJF79D8eHV3qFF1Jqww:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/69ca6596ab9f1a7c342978f8bd61be4d0f64ad8a/docs/api.adoc#L13)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Sorry, mislooked this yesterday.
> 
> The previous paragraph looks very poor and doesn't really explain what is inside. At the same time, really nice explanation is given in the “Introduction“ section.
> 
> Maybe remove the paragraph saying “Native Angular 2 directive for Polymer.” and the “Introduction” section title?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16)_

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/16)_

**Pull request merged**
