### PR TITLE
Update dependencies to Angular 2 final

### PR DESCRIPTION
**Pull request by tehapo**
No other changes than dependency versions, so I think no new release is required after merging this. 

However, it's nice to update these in order to officially support only the final release instead of RC versions.

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/89)

### CODE REVIEW

**Comment by samiheikki** [comment]
Should `typescript` devDependency be updated as well? In Angular 2 quickstart it is `^2.0.2`.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/89#-:-KRlVPOdwTBjRacXC7ou:b-avs905)_

**Comment by tehapo** [comment]
Done. Updated `concurrently`, `typescript` and `typings` dependencies to match the version ranges defined in the Angular 2 quickstart.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/89#-:-KRm-OZfNZSlIz2jmuBO:b4n6too)_

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/89#-:-KRm4d6oiqE6cmzePQcZ:bnfp4nl)_

**Comment by Chabane** [comment]
Thanks!

@manolo Can you publish the new version in NPM please?

**Comment by tehapo** [comment]
@Chabane I'll push out a release to npm in about five minutes. 😄

**Pull request merged**
