### PR TITLE
Feature/readme license

### PR DESCRIPTION
**Pull request by manolo**
Connected to #13

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/17)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[README.md, line 5 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJ5J64BPPmPCPrj5KMh:-KJ5J64BPPmPCPrj5KMi:1130459988) ([raw file](https://github.com/vaadin/angular2-polymer/blob/b23797eb476e2113d2084cba8a364ef9363d0b6e/README.md#L5)):_

> ``` Markdown
> 
> `angular2-polymer` is a directive factory that aims at bridging the gaps between using [Polymer](https://www.polymer-project.org) based Web Components in [Angular 2](https://angular.io/) applications.
> ```

Normally we have screenshots to illustrate our elements here.

Instead of a screenshot, let us add a brief usage example here, like you have in the ng-cli doc. It looks very descriptive, I think, and explains very well what this repository is for and how it is used.

---

_[README.md, line 39 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJ5I77C_jGYPocHEjeG:-KJ5I77DIsfUR5n_hbFa:-420946264) ([raw file](https://github.com/vaadin/angular2-polymer/blob/b23797eb476e2113d2084cba8a364ef9363d0b6e/README.md#L39)):_

> ``` Markdown
> For running Tests you need [Bower](http://bower.io) installed.
> 
> Then, you can download all bower dependencies needed by Tests.
> ```

“needed by _the tests_”.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17)_

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17)_

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[README.md, line 5 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJ5J64BPPmPCPrj5KMh:-KJ5t2_F_i08obY4apcP:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/b23797eb476e2113d2084cba8a364ef9363d0b6e/README.md#L5)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Normally we have screenshots to illustrate our elements here.
> 
> Instead of a screenshot, let us add a brief usage example here, like you have in the ng-cli doc. It looks very descriptive, I think, and explains very well what this repository is for and how it is used.
> </details>
> Done.

---

_[README.md, line 39 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJ5I77C_jGYPocHEjeG:-KJ5t32ckzdwlxvHqe5t:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/b23797eb476e2113d2084cba8a364ef9363d0b6e/README.md#L39)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> “needed by _the tests_”.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17)_

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17)_

**Comment by platosha** [comment]
:lgtm:

<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> #### Feature/readme license
> 
> Connected to #13
> 
> </details>

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-:-KJ6HYgnioliPnPf-mm5:1417088721)_

**Comment by platosha** [comment]
@magi42 please review this README file

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[docs/overview.adoc, line 10 [r4]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJF1oII4WkSxF0WO9lB:-KJF1oIJn3HNq-VIRWyo:-1399217569) ([raw file](https://github.com/vaadin/angular2-polymer/blob/88a61d3d57f22a214c32a8c343c2dcb5bc88d3e1/docs/overview.adoc#L10)):_

> ``` AsciiDoc
> = Angular 2 Integration
> 
> While Vaadin Elements are built using Polymer, you need the [literal]#https://github.com/vaadin/angular2-polymer[@vaadin/angular2-polymer]# directive to enable seamless usage within Angular 2 applications.
> ```

Maybe start with “Since”?

---

_[docs/overview.adoc, line 14 [r4]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJF1zDOCXeLmc9WhkwL:-KJF1zDOCXeLmc9WhkwM:-1558579701) ([raw file](https://github.com/vaadin/angular2-polymer/blob/88a61d3d57f22a214c32a8c343c2dcb5bc88d3e1/docs/overview.adoc#L14)):_

> ``` AsciiDoc
> The `angular2-polymer` is a directive factory that aims at bridging the gaps between using link:https://www.polymer-project.org[Polymer] based Web Components in link:https://angular.io/[Angular 2] applications.
> 
> It is able to scrap the Polymer element public API in order to define Angular 2 `outputs` and `inputs`, to apply the `ngControl` and the `ngForm` directives, and to observe DOM changes updating the element's DOM tree appropriately.
> ```

Better to say simply, “It scraps the Polymer element API”. Not only that it can scrap the API, but it also actually does it.  

---

_[docs/overview.adoc, line 18 [r4]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJF2OnDh-BhyIKgvAtg:-KJF2OnDh-BhyIKgvAth:-1692793915) ([raw file](https://github.com/vaadin/angular2-polymer/blob/88a61d3d57f22a214c32a8c343c2dcb5bc88d3e1/docs/overview.adoc#L18)):_

> ``` AsciiDoc
> == Quick Start
> 
> . Install the `angular2-polymer` directive, and the Polymer element you want to use.
> ```

“Install the `@vaadin/angular2-polymer` package and the Polymer element...”

---

_[docs/overview.adoc, line 35 [r4]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJF2aTgnC4rdfc4dbTb:-KJF2aTgnC4rdfc4dbTc:-1759383623) ([raw file](https://github.com/vaadin/angular2-polymer/blob/88a61d3d57f22a214c32a8c343c2dcb5bc88d3e1/docs/overview.adoc#L35)):_

> ``` AsciiDoc
> ----
> 
> . Use the Angular 2 directive in your code.
> ```

“Import the Angular 2 directives and use them in your code”.

The SystemJS import step is missing here. I feel, that SystemJS configuration changes are too hard to explain here. Though it's better to mention, that there is an import step, that developers should care about. So I suggest to rephrase as “Import ... and use ...”, as quoted above.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17)_

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[docs/overview.adoc, line 10 [r4]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJF1oII4WkSxF0WO9lB:-KJF5woUFb69veqA-Qby:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/88a61d3d57f22a214c32a8c343c2dcb5bc88d3e1/docs/overview.adoc#L10)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Maybe start with “Since”?
> </details>
> Done.

---

_[docs/overview.adoc, line 14 [r4]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJF1zDOCXeLmc9WhkwL:-KJF5H9a4kB12eIBPcxs:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/88a61d3d57f22a214c32a8c343c2dcb5bc88d3e1/docs/overview.adoc#L14)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Better to say simply, “It scraps the Polymer element API”. Not only that it can scrap the API, but it also actually does it.  
> </details>
> Done.

---

_[docs/overview.adoc, line 18 [r4]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJF2OnDh-BhyIKgvAtg:-KJF5MDxbq_llB-7UykT:-499146009) ([raw file](https://github.com/vaadin/angular2-polymer/blob/88a61d3d57f22a214c32a8c343c2dcb5bc88d3e1/docs/overview.adoc#L18)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> “Install the `@vaadin/angular2-polymer` package and the Polymer element...”
> </details>
> Done.

---

_[docs/overview.adoc, line 35 [r4]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17#-KJF2aTgnC4rdfc4dbTb:-KJF5pzwh3WZxtvxdqjd:1062862771) ([raw file](https://github.com/vaadin/angular2-polymer/blob/88a61d3d57f22a214c32a8c343c2dcb5bc88d3e1/docs/overview.adoc#L35)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> “Import the Angular 2 directives and use them in your code”.
> 
> The SystemJS import step is missing here. I feel, that SystemJS configuration changes are too hard to explain here. Though it's better to mention, that there is an import step, that developers should care about. So I suggest to rephrase as “Import ... and use ...”, as quoted above.
> </details>
> I will update this when public links in docsite works.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17)_

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/17)_

**Pull request merged**
