### PR TITLE
Add directive for IronCheckedElementBehavior

### LINKED ISSUE #45: Checkbox is not checked using value attribute
``` typescript
import { Component } from '@angular/core';
import { PolymerElement } from '@vaadin/angular2-polymer';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  directives: [
    PolymerElement('paper-checkbox'),
    PolymerElement('paper-button'),
  ]
})
export class AppComponent {

  public test: boolean = true;

}
```

``` html
<p>
  Value of test: {{test}}
  <paper-checkbox [(value)]="test">Template</paper-checkbox>
</p>
```

bildschirmfoto 2016-07-15 um 00 26 20

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #45

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer/53)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

_[tests.html, line 10 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/53#-KNqT1-A73vwbGObZHSt:-KNqT1-A73vwbGObZHSu:1641112069) ([raw file](https://github.com/vaadin/angular2-polymer/blob/3e0ccb5c1a28bbaff9e01e1bdca4e0db0971d12c/tests.html#L10)):_

> ``` HTML
>   <link rel="import" href="bower_components/polymer/polymer.html">
>   <link rel="import" href="src/test-element.html">
>   <link rel="import" href="bower_components/paper-checkbox/paper-checkbox.html">
> ```

Let’s put this line above the import of “src/test-element.html" for consistency: global imports come before local ones.

---

_[src/polymer-element.spec.ts, line 206 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/53#-KNqTFQOTFRLKD8OKYi1:-KNqTFQPr0k_sS-sk8Us:1585328248) ([raw file](https://github.com/vaadin/angular2-polymer/blob/3e0ccb5c1a28bbaff9e01e1bdca4e0db0971d12c/src/polymer-element.spec.ts#L206)):_

> ``` XML
> 
>       it('should set default value', () => {
>         var checkedElement = fixture.debugElement.query(By.css('paper-checkbox')).nativeElement;
> ```

What about declaring var checkedElement at the scope of `describe('Checked Element inside Form', () => {...})`, and extracting the repetitive query call into a beforeEach block?

---

_[src/polymer-element.ts, line 335 [r1]](https://reviewable.io:443/reviews/vaadin/angular2-polymer/53#-KNqYXNmjX9KuS-ha1BK:-KNqYXNmjX9KuS-ha1BL:-2070470923) ([raw file](https://github.com/vaadin/angular2-polymer/blob/3e0ccb5c1a28bbaff9e01e1bdca4e0db0971d12c/src/polymer-element.ts#L335)):_

> ``` XML
>     directives.push(checkedElementDirective);
>     directives.push(validationDirective);
>   } else if (isFormElement) {
> ```

Let’s get rid of the duplicated `validationDirective` push line.

I think, the nested branching is more logical here, and also easier to read:

``` javascript
if (isFormElement) {
  directives.push(isCheckedElement ? checkedElementDirective : formElementDirective);
  directives.push(validationDirective);
}
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/53)_

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer/53)_

**Comment by tehapo** [comment]
Commit https://github.com/vaadin/angular2-polymer/commit/7a3add59fdee089ee2677394993f15fac7226521 includes an alternative version of this fix based on top of the `feature/new-forms-api` branch.

**Comment by tehapo** [comment]
Closing this one in favor of #62. Reopen if needed.

**Pull request closed without merging**
